name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # TODO build, test and deploy project

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          # TODO insert your <Variant> and <ServiceName>
          collection: <Variant>/postman/[rsoi] postman_collection.json
          environment: <Variant>/postman/[rsoi][heroku] postman_environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'
          envVar: '[{ "key":"serviceName", "value":"<ServiceName>" }, { "key":"herokuApiToken", "value":"${{secrets.HEROKU_API_KEY}}" }]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true
